name: 英語でニャンパ
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78099
title: 英語でニャンパ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6efd2'
    - '#af8a5e'
    - '#d81b21'
    - '#000002'
    - '#8b4825'
  brandStrength: 0.58847591211088
  lightness: 0.33458024193532765
  saturation: 0.6297125446144491
  rhythmicContrast: 0.5777729814872146
purpose: []
